apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  namespace: fcs-notifications
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  KafkaSettings__BootstrapServers: kafka-service.fcs-infra.svc.cluster.local:29092
  KafkaSettings__GroupId: fcs-notifications-consumer-group
  KafkaSettings__Topics__EmailNotification: email-notification-requested
  KafkaSettings__ConsumerTimeoutMs: "100"
  ResendTemplates__DonorWelcomeTemplateId: 5f3a8ba3-a08a-415d-9d9d-a43ef8ae36d6
  ResendTemplates__DonationCreatedTemplateId: 8b9a9067-8ce8-4e2b-b2bd-b5765c57c600
  ResendTemplates__DonationProcessedTemplateId: 0945c3f4-74c1-4204-a09c-17526f4aa65f
  Observability__ServiceName: Fcs.Notifications
  Observability__EnableOtlpExporter: "true"
  Observability__OtlpEndpoint: http://otel-collector-service.fcs-infra.svc.cluster.local:4318
  Observability__OtlpAuthHeader: ""
