apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: notifications-runtime
  namespace: fcs-notifications
spec:
  infisicalAuthRef:
    name: fcs-platform-auth
    namespace: infisical-operator-system
  syncOptions:
    refreshInterval: 5m
    instantUpdates: false
  sources:
    - projectSlug: fcs-platform-dd-uk
      environmentSlug: prod
      secretPath: /platform
  targets:
    - name: notifications-runtime
      namespace: fcs-notifications
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          Resend__ApiKey: '{{ secretFrom "/platform" "resend-api-key" }}'
